# Generated by Django 6.0.5 on 2026-06-16 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('reason', models.TextField(verbose_name='Motivo')),
                ('start_date', models.DateTimeField(verbose_name='Início')),
                ('end_date', models.DateTimeField(verbose_name='Previsão de término')),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('active', 'Em andamento'), ('finished', 'Finalizada'), ('cancelled', 'Cancelada')], default='scheduled', max_length=20)),
                ('disconnect_users', models.BooleanField(default=False, verbose_name='Deslogar usuários conectados')),
                ('block_login', models.BooleanField(default=True, verbose_name='Bloquear novos logins')),
                ('show_maintenance_page', models.BooleanField(default=True, verbose_name='Exibir página de manutenção')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Criada'), ('started', 'Iniciada'), ('finished', 'Finalizada'), ('cancelled', 'Cancelada')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='system.maintenancewindow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', 'Operando'), ('maintenance', 'Manutenção')], default='online', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.maintenancewindow')),
            ],
        ),
    ]
