# Generated by Django 6.0.5 on 2026-06-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='under_maintenance',
        ),
        migrations.AddField(
            model_name='system',
            name='status',
            field=models.CharField(choices=[('operational', '🟢 Operando'), ('maintenance', '🔴 Em manutenção')], default='operational', max_length=20),
        ),
    ]
