# Generated by Django 6.0.5 on 2026-06-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_system_under_maintenance_system_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='status',
        ),
        migrations.AddField(
            model_name='system',
            name='under_maintenance',
            field=models.BooleanField(default=False, verbose_name='Em manutenção'),
        ),
    ]
