# Generated by Django 6.0.5 on 2026-06-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_system_status_system_under_maintenance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='System',
        ),
    ]
