# Generated by Django 6.0.5 on 2026-06-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='authenticator_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='authenticator_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='authenticator_secret',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
