# Generated by Django 6.0.6 on 2026-07-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_profile_authenticator_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='indicators_events',
            field=models.BooleanField(default=True),
        ),
    ]
