# Generated by Django 6.0.5 on 2026-05-20 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentmethod',
            name='descript',
        ),
        migrations.RemoveField(
            model_name='assignmentmethod',
            name='name',
        ),
        migrations.AddField(
            model_name='assignmentmethod',
            name='method_type',
            field=models.CharField(choices=[('DEMAND', 'Por demanda'), ('RANDOM', 'Aleatório'), ('SPECIFIC', 'Técnicos específicos')], default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmentmethod',
            name='technicians',
            field=models.ManyToManyField(blank=True, related_name='assignment_methods', to=settings.AUTH_USER_MODEL),
        ),
    ]
