# Generated by Django 6.0.5 on 2026-05-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0002_remove_assignmentmethod_descript_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentmethod',
            name='name',
            field=models.CharField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignmentmethod',
            name='method_type',
            field=models.CharField(choices=[('DEMAND', 'Por demanda'), ('RANDOM', 'Aleatório'), ('SPECIFIC', 'Técnicos específicos')], max_length=20),
        ),
    ]
