# Generated by Django 6.0.5 on 2026-06-18 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_ticket_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketinteraction',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(max_length=550),
        ),
        migrations.AlterField(
            model_name='ticketinteraction',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='ticket.ticket'),
        ),
        migrations.CreateModel(
            name='TicketInteractionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_interactions/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ticket.ticketinteraction')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
