# Generated by Django 6.0.5 on 2026-05-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
