# Generated by Django 6.0.5 on 2026-06-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_kind',
            field=models.CharField(blank=True, choices=[('', 'Nenhuma'), ('solution_validation', 'Validacao de solucao'), ('service_evaluation', 'Avaliacao de atendimento'), ('approval_request', 'Solicitacao de autorizacao')], default='', max_length=40),
        ),
    ]
